# Generated by Django 3.1.3 on 2022-01-21 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220121_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='Owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='Target',
        ),
        migrations.AddField(
            model_name='follow',
            name='Target',
            field=models.ManyToManyField(null=True, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
