# Generated by Django 3.1.3 on 2022-01-21 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20220121_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='Target',
            field=models.ManyToManyField(related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
